#!/bin/bash

# Author: Simon Brandt
# E-Mail: simon.brandt@uni-greifswald.de
# Last Modification: 2025-06-27

# Warning: The script will stage all changes in the Markdown files.

# Run the MarkdownTools for any Markdown file to be committed.
# As `git diff` outputs only the filenames relative to the repository's
# base directory, switch to this directory, if the script is called from
# `.git/hooks` and fetch the absolute path of the directory from
# `git rev-parse` to prepend it to each filename.
if [[ "${PWD: -10}" == ".git/hooks" ]]; then
    cd ../.. || exit 1
fi

mapfile -t files < <(git diff --cached --name-only HEAD)
dir="$(git rev-parse --show-toplevel)"

for file in "${files[@]}"; do
    if [[ "${file: -3}" != ".md" ]]; then
        continue
    elif [[ "${file}" == */* ]]; then
        cd "${file%/*.md}" || exit 1
    fi

    file="${dir}/${file}"
    bash create_toc.sh \
        --in-place \
        --exclude-headings="Table of contents" \
        --exclude-levels=1 \
        -- \
        "${file}"
    bash include_file.sh "${file}"
    bash create_captions.sh "${file}"
    bash create_toc.sh \
        --in-place \
        --exclude-headings="Table of contents" \
        --exclude-levels=1 \
        -- \
        "${file}"
    bash split_sections.sh \
        --to-headings \
        -- \
        "${file}"

    git add '*.md'
done
